/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsConnectionConfig {
  host: string
  port?: number
  database: string
  user: string
  password: string
  ssl?: boolean
  rejectUnauthorized?: boolean
  sslClientHostnameValidation?: string
  caCert?: string
  securityMechanism?: string
  encryptionAlgorithm?: string
  credentialEncoding?: string
  encryptedPasswordEncoding?: string
  encryptedPasswordTokenEncoding?: string
  connectTimeout?: number
  queryTimeout?: number
  frameDrainTimeout?: number
  currentSchema?: string
  typeDefinitionName?: string
  fetchSize?: number
}
export interface JsQueryResult {
  rows: Array<any>
  rowCount: number
  columns: Array<JsColumnInfo>
  diagnostics: Array<string>
  resultSets: Array<JsQueryResult>
  outputParameters: Array<any>
}
export interface JsColumnInfo {
  name: string
  typeName: string
  db2TypeName?: string
  nullable: boolean
  precision?: number
  scale?: number
}
export interface JsServerInfo {
  productName: string
  serverRelease: string
}
export interface JsPoolConfig {
  host: string
  port?: number
  database: string
  user: string
  password: string
  ssl?: boolean
  rejectUnauthorized?: boolean
  sslClientHostnameValidation?: string
  caCert?: string
  securityMechanism?: string
  encryptionAlgorithm?: string
  credentialEncoding?: string
  encryptedPasswordEncoding?: string
  encryptedPasswordTokenEncoding?: string
  connectTimeout?: number
  queryTimeout?: number
  frameDrainTimeout?: number
  currentSchema?: string
  typeDefinitionName?: string
  fetchSize?: number
  minConnections?: number
  maxConnections?: number
  idleTimeout?: number
  maxLifetime?: number
  healthCheckInterval?: number
}
/** Per-call result formatting; object rows are the compatible default. */
export interface JsQueryOptions {
  rowMode?: import('./types').RowMode
}
export declare class JsClient {
  constructor(config: JsConnectionConfig)
  connect(): Promise<void>
  query(sql: string, params?: import('./types').QueryParameters | null, options?: import('./types').QueryOptions<'object'> | null): Promise<import('./types').QueryResult>;
  query(sql: string, params: import('./types').QueryParameters | null | undefined, options: import('./types').QueryOptions<'array'>): Promise<import('./types').QueryResult<'array'>>;
  query(sql: string, params: import('./types').QueryParameters | null | undefined, options: import('./types').QueryOptions | null | undefined): Promise<import('./types').QueryResult<import('./types').RowMode>>
  /** Cancel a running LUW activity without waiting for query() to finish. */
  cancel(): Promise<boolean>
  prepare(sql: string): Promise<JsPreparedStatement>
  beginTransaction(): Promise<JsTransaction>
  close(): Promise<void>
  serverInfo(): Promise<JsServerInfo>
}
export declare class JsPool {
  constructor(config: JsPoolConfig)
  connect(): Promise<void>
  warmup(): Promise<number>
  query(sql: string, params?: import('./types').QueryParameters | null, options?: import('./types').QueryOptions<'object'> | null): Promise<import('./types').QueryResult>;
  query(sql: string, params: import('./types').QueryParameters | null | undefined, options: import('./types').QueryOptions<'array'>): Promise<import('./types').QueryResult<'array'>>;
  query(sql: string, params: import('./types').QueryParameters | null | undefined, options: import('./types').QueryOptions | null | undefined): Promise<import('./types').QueryResult<import('./types').RowMode>>
  acquire(): Promise<JsClient>
  release(client: JsClient): Promise<void>
  close(): Promise<void>
  idleCount(): Promise<number>
  activeCount(): Promise<number>
  totalCount(): Promise<number>
  maxConnections(): number
}
export declare class JsPreparedStatement {
  execute(params?: import('./types').QueryParameters | null, options?: import('./types').QueryOptions<'object'> | null): Promise<import('./types').QueryResult>;
  execute(params: import('./types').QueryParameters | null | undefined, options: import('./types').QueryOptions<'array'>): Promise<import('./types').QueryResult<'array'>>;
  execute(params: import('./types').QueryParameters | null | undefined, options: import('./types').QueryOptions | null | undefined): Promise<import('./types').QueryResult<import('./types').RowMode>>
  /**
   * Execute the prepared statement as a batch with multiple rows of parameters.
   * Each element of `param_rows` is an array of parameter values for one row.
   */
  executeBatch(paramRows: import('./types').QueryParameters[], options?: import('./types').QueryOptions<'object'> | null): Promise<import('./types').QueryResult>;
  executeBatch(paramRows: import('./types').QueryParameters[], options: import('./types').QueryOptions<'array'>): Promise<import('./types').QueryResult<'array'>>;
  executeBatch(paramRows: import('./types').QueryParameters[], options: import('./types').QueryOptions | null | undefined): Promise<import('./types').QueryResult<import('./types').RowMode>>
  close(): Promise<void>
}
export declare class JsTransaction {
  query(sql: string, params?: import('./types').QueryParameters | null, options?: import('./types').QueryOptions<'object'> | null): Promise<import('./types').QueryResult>;
  query(sql: string, params: import('./types').QueryParameters | null | undefined, options: import('./types').QueryOptions<'array'>): Promise<import('./types').QueryResult<'array'>>;
  query(sql: string, params: import('./types').QueryParameters | null | undefined, options: import('./types').QueryOptions | null | undefined): Promise<import('./types').QueryResult<import('./types').RowMode>>
  /** Prepare a SQL statement within this transaction. */
  prepare(sql: string): Promise<JsPreparedStatement>
  commit(): Promise<void>
  rollback(): Promise<void>
}
