/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsConnectionConfig {
  host: string
  port?: number
  database: string
  user: string
  password: string
  ssl?: boolean
  rejectUnauthorized?: boolean
  sslClientHostnameValidation?: string
  caCert?: string
  securityMechanism?: string
  encryptionAlgorithm?: string
  credentialEncoding?: string
  encryptedPasswordEncoding?: string
  encryptedPasswordTokenEncoding?: string
  connectTimeout?: number
  queryTimeout?: number
  frameDrainTimeout?: number
  currentSchema?: string
  typeDefinitionName?: string
  fetchSize?: number
}
export interface JsQueryResult {
  rows: Array<any>
  rowCount: number
  columns: Array<JsColumnInfo>
  diagnostics: Array<string>
  resultSets: Array<JsQueryResult>
  outputParameters: Array<any>
}
export interface JsColumnInfo {
  name: string
  typeName: string
  db2TypeName?: string
  nullable: boolean
  precision?: number
  scale?: number
}
export interface JsServerInfo {
  productName: string
  serverRelease: string
}
export interface JsPoolConfig {
  host: string
  port?: number
  database: string
  user: string
  password: string
  ssl?: boolean
  rejectUnauthorized?: boolean
  sslClientHostnameValidation?: string
  caCert?: string
  securityMechanism?: string
  encryptionAlgorithm?: string
  credentialEncoding?: string
  encryptedPasswordEncoding?: string
  encryptedPasswordTokenEncoding?: string
  connectTimeout?: number
  queryTimeout?: number
  frameDrainTimeout?: number
  currentSchema?: string
  typeDefinitionName?: string
  fetchSize?: number
  minConnections?: number
  maxConnections?: number
  idleTimeout?: number
  maxLifetime?: number
  healthCheckInterval?: number
}
/** Per-call result formatting; object rows are the compatible default. */
export interface JsQueryOptions {
  rowMode?: import('./types').RowMode
}
export declare class JsClient {
  constructor(config: JsConnectionConfig)
  connect(): Promise<void>
  query<M extends import('./types').RowMode = 'object'>(sql: string, params?: Array<string | number | bigint | boolean | Date | null | Uint8Array | ArrayBuffer | number[]> | undefined | null, options?: import('./types').QueryOptions<M> | undefined | null): Promise<import('./types').QueryResult<M>>
  /** Cancel a running LUW activity without waiting for query() to finish. */
  cancel(): Promise<boolean>
  prepare(sql: string): Promise<JsPreparedStatement>
  beginTransaction(): Promise<JsTransaction>
  close(): Promise<void>
  serverInfo(): Promise<JsServerInfo>
}
export declare class JsPool {
  constructor(config: JsPoolConfig)
  connect(): Promise<void>
  warmup(): Promise<number>
  query<M extends import('./types').RowMode = 'object'>(sql: string, params?: Array<string | number | bigint | boolean | Date | null | Uint8Array | ArrayBuffer | number[]> | undefined | null, options?: import('./types').QueryOptions<M> | undefined | null): Promise<import('./types').QueryResult<M>>
  acquire(): Promise<JsClient>
  release(client: JsClient): Promise<void>
  close(): Promise<void>
  idleCount(): Promise<number>
  activeCount(): Promise<number>
  totalCount(): Promise<number>
  maxConnections(): number
}
export declare class JsPreparedStatement {
  execute<M extends import('./types').RowMode = 'object'>(params?: Array<string | number | bigint | boolean | Date | null | Uint8Array | ArrayBuffer | number[]> | undefined | null, options?: import('./types').QueryOptions<M> | undefined | null): Promise<import('./types').QueryResult<M>>
  /**
   * Execute the prepared statement as a batch with multiple rows of parameters.
   * Each element of `param_rows` is an array of parameter values for one row.
   */
  executeBatch<M extends import('./types').RowMode = 'object'>(paramRows: Array<Array<string | number | bigint | boolean | Date | null | Uint8Array | ArrayBuffer | number[]>>, options?: import('./types').QueryOptions<M> | undefined | null): Promise<import('./types').QueryResult<M>>
  close(): Promise<void>
}
export declare class JsTransaction {
  query<M extends import('./types').RowMode = 'object'>(sql: string, params?: Array<string | number | bigint | boolean | Date | null | Uint8Array | ArrayBuffer | number[]> | undefined | null, options?: import('./types').QueryOptions<M> | undefined | null): Promise<import('./types').QueryResult<M>>
  /** Prepare a SQL statement within this transaction. */
  prepare(sql: string): Promise<JsPreparedStatement>
  commit(): Promise<void>
  rollback(): Promise<void>
}
