// Re-export NAPI-generated types with clean names.
// index.d.ts is auto-generated by napi build — don't edit it directly.

export {
  JsConnectionConfig as ConnectionConfig,
  JsQueryResult as QueryResult,
  JsColumnInfo as ColumnInfo,
  JsServerInfo as ServerInfo,
  JsPoolConfig as PoolConfig,
  JsClient as Client,
  JsPool as Pool,
  JsPreparedStatement as PreparedStatement,
  JsTransaction as Transaction,
} from './index.js'

// Also re-export the original Js-prefixed names for backwards compatibility
export {
  JsConnectionConfig,
  JsQueryResult,
  JsColumnInfo,
  JsServerInfo,
  JsPoolConfig,
  JsClient,
  JsPool,
  JsPreparedStatement,
  JsTransaction,
} from './index.js'
