/// <reference lib="es2018.asynciterable" />

// Re-export NAPI-generated types with clean names.
// index.d.ts is auto-generated by napi build; do not edit it directly.

export {
  JsConnectionConfig as ConnectionConfig,
  JsColumnInfo as ColumnInfo,
  JsServerInfo as ServerInfo,
  JsPoolConfig as PoolConfig,
  JsClient,
  JsPool,
  JsPreparedStatement,
  JsTransaction,
} from './index.js'

export {
  JsClient as NativeClient,
  JsPool as NativePool,
  JsPreparedStatement as NativePreparedStatement,
  JsTransaction as NativeTransaction,
} from './index.js'

import type {
  JsClient,
  JsConnectionConfig,
  JsQueryResult,
  JsServerInfo,
  JsPoolConfig,
  JsColumnInfo,
} from './index.js'

export type ConnectionString = string | Record<string, any>
export type BinaryParameter = Uint8Array | ArrayBuffer | number[]
export type QueryParameter = string | number | bigint | boolean | Date | null | BinaryParameter
export type QueryParameters = QueryParameter[]

/** Object rows are the compatible default; array entries follow columns by index. */
export type RowMode = 'object' | 'array'
export type QueryOptions<M extends RowMode = RowMode> = [M] extends ['array']
  ? { rowMode: M }
  : { rowMode?: M }
export type QueryRow<M extends RowMode = 'object'> = M extends 'array' ? any[] : Record<string, any>
export type QueryResult<M extends RowMode = 'object'> = M extends RowMode
  ? Omit<JsQueryResult, 'rows' | 'resultSets'> & {
      rows: QueryRow<M>[]
      resultSets: QueryResult<M>[]
    }
  : never

export type QueryCallback<M extends RowMode = 'object'> = (err: Db2Error | null, result: QueryResult<M>) => void

export type SqlQuery<M extends RowMode = RowMode> = {
  sql: string
  params?: QueryParameters
  noResults?: boolean
} & QueryOptions<M>

type RowStreamEventArgs<M extends RowMode, E extends string | symbol> =
  E extends 'data' ? [row: QueryRow<M>] :
  E extends 'error' ? [error: Db2Error] :
  E extends 'close' | 'end' | 'pause' | 'readable' | 'resume' ? [] : any[]
type RowStreamListener<M extends RowMode, E extends string | symbol> = (...args: RowStreamEventArgs<M, E>) => void

// Structural Writable contract used by Node's pipe(), without ambient Node types.
interface RowStreamDestination {
  readonly writable: boolean
  write(chunk: any): boolean
  end(): unknown
  on(event: string | symbol, listener: (...args: any[]) => void): unknown
  once(event: string | symbol, listener: (...args: any[]) => void): unknown
  prependListener(event: string | symbol, listener: (...args: any[]) => void): unknown
  removeListener(event: string | symbol, listener: (...args: any[]) => void): unknown
  listenerCount(event: string | symbol): number
  emit(event: string | symbol, ...args: any[]): boolean
}

/** Object-mode Readable iteration, events and controls; no @types/node required. */
export interface RowStream<out M extends RowMode = 'object'> extends AsyncIterable<QueryRow<M>> {
  readonly readable: boolean
  readonly readableAborted: boolean
  readonly readableDidRead: boolean
  readonly readableEnded: boolean
  readonly readableFlowing: boolean | null
  readonly readableHighWaterMark: number
  readonly readableLength: number
  readonly readableObjectMode: true
  readonly destroyed: boolean
  readonly closed: boolean
  readonly errored: Error | null
  read(size?: number): QueryRow<M> | null
  pause(): this
  resume(): this
  isPaused(): boolean
  destroy(error?: Error): this
  pipe<T extends RowStreamDestination>(destination: T, options?: { end?: boolean | undefined }): T
  unpipe(destination?: RowStreamDestination): this
  on<E extends string | symbol>(event: E, listener: RowStreamListener<M, E>): this
  once<E extends string | symbol>(event: E, listener: RowStreamListener<M, E>): this
  addListener<E extends string | symbol>(event: E, listener: RowStreamListener<M, E>): this
  prependListener<E extends string | symbol>(event: E, listener: RowStreamListener<M, E>): this
  prependOnceListener<E extends string | symbol>(event: E, listener: RowStreamListener<M, E>): this
  off<E extends string | symbol>(event: E, listener: RowStreamListener<M, E>): this
  removeListener<E extends string | symbol>(event: E, listener: RowStreamListener<M, E>): this
  removeAllListeners(event?: string | symbol): this
  setMaxListeners(count: number): this
  getMaxListeners(): number
  listenerCount(event: string | symbol): number
  listeners<E extends string | symbol>(event: E): RowStreamListener<M, E>[]
  rawListeners<E extends string | symbol>(event: E): RowStreamListener<M, E>[]
  emit<E extends string | symbol>(event: E, ...args: RowStreamEventArgs<M, E>): boolean
  eventNames(): Array<string | symbol>
  [Symbol.asyncIterator](): AsyncIterableIterator<QueryRow<M>>
}

/** Stable driver classifications; server errors instead retain SQLSTATE/SQLCODE. */
export type DriverErrorCode = 'DB2_PARAMETER_COUNT' | 'DB2_PARAMETER_TYPE' | 'DB2_PROTOCOL' | 'DB2_INVALID_OPTION'
export interface Db2Error extends Error {
  code?: string
  driverCode?: DriverErrorCode
  sqlstate?: string
  sqlcode?: number
  retryable?: boolean
}

export interface IbmDbPoolOptions {
  maxPoolSize?: number
  maxConnections?: number
  connectTimeout?: number
  queryTimeout?: number
  idleTimeout?: number
  maxLifetime?: number
  healthCheckInterval?: number
  currentSchema?: string
  fetchSize?: number
  ssl?: boolean
  rejectUnauthorized?: boolean
  sslClientHostnameValidation?: string
}

// Array overloads require a runtime discriminant. Omitted options select object
// rows; a dynamic or optional mode exposes both possible result shapes.
export class Client {
  constructor(config: JsConnectionConfig)
  connect(): Promise<void>
  query(sql: string, params: QueryParameters | null | undefined, options: QueryOptions<'array'>): Promise<QueryResult<'array'>>
  query(sql: string, params?: QueryParameters | null, options?: QueryOptions<'object'> | null): Promise<QueryResult>
  query(sql: string, params: QueryParameters | null | undefined, options: QueryOptions | null | undefined): Promise<QueryResult<RowMode>>
  prepare(sql: string): Promise<PreparedStatement>
  beginTransaction(): Promise<Transaction>
  close(): Promise<void>
  serverInfo(): Promise<JsServerInfo>
  cancel(): Promise<boolean>
}

export class Pool {
  constructor(config?: JsPoolConfig | IbmDbPoolOptions)
  connect(callback?: (err?: Error | null) => void): Promise<void> | void
  warmup(callback?: (err: Error | null, created?: number) => void): Promise<number> | void
  query(sql: string, params: QueryParameters | null | undefined, options: QueryOptions<'array'>): Promise<QueryResult<'array'>>
  query(sql: string, params?: QueryParameters | null, options?: QueryOptions<'object'> | null): Promise<QueryResult>
  query(sql: string, params: QueryParameters | null | undefined, options: QueryOptions | null | undefined): Promise<QueryResult<RowMode>>
  query(sql: string, params: QueryParameters | null | undefined, options: QueryOptions<'array'>, callback: QueryCallback<'array'>): void
  query(sql: string, params: QueryParameters | null | undefined, options: QueryOptions<'object'> | null | undefined, callback: QueryCallback): void
  query(sql: string, params: QueryParameters | null | undefined, options: QueryOptions | null | undefined, callback: QueryCallback<RowMode>): void
  query(sql: string, callback: QueryCallback): void
  query(sql: string, params: QueryParameters | null | undefined, callback: QueryCallback): void
  acquire(): Promise<Client>
  acquire(callback: (err: Error | null, client: Client) => void): void
  release(client: Client | JsClient, callback?: (err?: Error | null) => void): Promise<void> | void
  close(callback?: (err?: Error | null) => void): Promise<void> | void
  idleCount(): Promise<number>
  activeCount(): Promise<number>
  totalCount(): Promise<number>
  maxConnections(callback?: (err: Error | null, count?: number) => void): number | void
  open(connectionString: ConnectionString, callback: (err: Error | null, conn: Database) => void): void
  open(connectionString: ConnectionString): Promise<Database>
  init(size: number, connectionString: ConnectionString): boolean
  initAsync(size: number, connectionString: ConnectionString, callback?: (err?: Error | null) => void): Promise<void> | void
  setMaxPoolSize(size: number): boolean
  setConnectTimeout(timeout: number): boolean
}

export class Db2Pool {
  constructor(config: JsPoolConfig)
  connect(): Promise<void>
  warmup(): Promise<number>
  query(sql: string, params: QueryParameters | null | undefined, options: QueryOptions<'array'>): Promise<QueryResult<'array'>>
  query(sql: string, params?: QueryParameters | null, options?: QueryOptions<'object'> | null): Promise<QueryResult>
  query(sql: string, params: QueryParameters | null | undefined, options: QueryOptions | null | undefined): Promise<QueryResult<RowMode>>
  acquire(): Promise<Client>
  release(client: Client | JsClient): Promise<void>
  close(): Promise<void>
  idleCount(): Promise<number>
  activeCount(): Promise<number>
  totalCount(): Promise<number>
  maxConnections(): number
}

export class PreparedStatement {
  execute(params: QueryParameters | null | undefined, options: QueryOptions<'array'>): Promise<QueryResult<'array'>>
  execute(params?: QueryParameters | null, options?: QueryOptions<'object'> | null): Promise<QueryResult>
  execute(params: QueryParameters | null | undefined, options: QueryOptions | null | undefined): Promise<QueryResult<RowMode>>
  executeBatch(paramRows: QueryParameters[], options: QueryOptions<'array'>): Promise<QueryResult<'array'>>
  executeBatch(paramRows: QueryParameters[], options?: QueryOptions<'object'> | null): Promise<QueryResult>
  executeBatch(paramRows: QueryParameters[], options: QueryOptions | null | undefined): Promise<QueryResult<RowMode>>
  close(): Promise<void>
}

export class Transaction {
  query(sql: string, params: QueryParameters | null | undefined, options: QueryOptions<'array'>): Promise<QueryResult<'array'>>
  query(sql: string, params?: QueryParameters | null, options?: QueryOptions<'object'> | null): Promise<QueryResult>
  query(sql: string, params: QueryParameters | null | undefined, options: QueryOptions | null | undefined): Promise<QueryResult<RowMode>>
  prepare(sql: string): Promise<PreparedStatement>
  commit(): Promise<void>
  rollback(): Promise<void>
}

export interface Sqlca {
  rowCount: number
  columns: JsColumnInfo[]
  diagnostics: string[]
}

export type IbmDbCallback<T> = (err: Error | null, value: T, sqlca?: Sqlca) => void

// Explicit covariance prevents conditional row types from making modes bivariant.
export class ODBCResult<out M extends RowMode = 'object'> {
  resultSets: QueryResult<M>[]
  outputParameters: any[]
  rows: QueryRow<M>[]
  columns: JsColumnInfo[]
  rowCount: number
  diagnostics: string[]
  fetch(callback: (err: Error | null, row: QueryRow<M> | false) => void): void
  fetch(): Promise<QueryRow<M> | false>
  fetchAll(callback: (err: Error | null, rows: QueryRow<M>[]) => void): void
  fetchAll(): Promise<QueryRow<M>[]>
  fetchN(count: number, callback: (err: Error | null, rows: QueryRow<M>[]) => void): void
  fetchN(count: number): Promise<QueryRow<M>[]>
  close(callback?: (err?: Error | null) => void): Promise<void> | void
}

export class ODBCStatement {
  bind(params: QueryParameters, callback?: (err?: Error | null) => void): Promise<void> | void
  execute(callback: (err: Error | null, result: ODBCResult, outparams?: any) => void): void
  execute(params?: QueryParameters): Promise<ODBCResult>
  execute(params: QueryParameters, callback: (err: Error | null, result: ODBCResult, outparams?: any) => void): void
  executeNonQuery(params?: QueryParameters): Promise<number>
  executeNonQuery(params: QueryParameters, callback: (err: Error | null, rowCount: number) => void): void
  close(callback?: (err?: Error | null) => void): Promise<void> | void
}

export class Database {
  open(connectionString: ConnectionString, callback: (err: Error | null, result?: boolean) => void): void
  open(connectionString: ConnectionString, options: Record<string, any>, callback: (err: Error | null, result?: boolean) => void): void
  open(connectionString: ConnectionString, options?: Record<string, any>): Promise<boolean>
  query(sql: SqlQuery<'array'>, params?: QueryParameters): Promise<QueryRow<'array'>[]>
  query(sql: SqlQuery<'array'>, callback: IbmDbCallback<QueryRow<'array'>[]>): void
  query(sql: SqlQuery<'array'>, params: QueryParameters, callback: IbmDbCallback<QueryRow<'array'>[]>): void
  query(sql: string | SqlQuery<'object'>, params?: QueryParameters): Promise<QueryRow<'object'>[]>
  query(sql: string | SqlQuery<'object'>, callback: IbmDbCallback<QueryRow<'object'>[]>): void
  query(sql: string | SqlQuery<'object'>, params: QueryParameters, callback: IbmDbCallback<QueryRow<'object'>[]>): void
  query(sql: string | SqlQuery, params?: QueryParameters): Promise<QueryRow<RowMode>[]>
  query(sql: string | SqlQuery, callback: IbmDbCallback<QueryRow<RowMode>[]>): void
  query(sql: string | SqlQuery, params: QueryParameters, callback: IbmDbCallback<QueryRow<RowMode>[]>): void
  queryResult(sql: SqlQuery<'array'>, params?: QueryParameters): Promise<ODBCResult<'array'>>
  queryResult(sql: SqlQuery<'array'>, callback: (err: Db2Error | null, result: ODBCResult<'array'>, outparams?: any) => void): void
  queryResult(sql: SqlQuery<'array'>, params: QueryParameters, callback: (err: Db2Error | null, result: ODBCResult<'array'>, outparams?: any) => void): void
  queryResult(sql: string | SqlQuery<'object'>, params?: QueryParameters): Promise<ODBCResult<'object'>>
  queryResult(sql: string | SqlQuery<'object'>, callback: (err: Db2Error | null, result: ODBCResult<'object'>, outparams?: any) => void): void
  queryResult(sql: string | SqlQuery<'object'>, params: QueryParameters, callback: (err: Db2Error | null, result: ODBCResult<'object'>, outparams?: any) => void): void
  queryResult(sql: string | SqlQuery, params?: QueryParameters): Promise<ODBCResult<RowMode>>
  queryResult(sql: string | SqlQuery, callback: (err: Db2Error | null, result: ODBCResult<RowMode>, outparams?: any) => void): void
  queryResult(sql: string | SqlQuery, params: QueryParameters, callback: (err: Db2Error | null, result: ODBCResult<RowMode>, outparams?: any) => void): void
  queryStream(sql: SqlQuery<'array'>, params?: QueryParameters): RowStream<'array'>
  queryStream(sql: string | SqlQuery<'object'>, params?: QueryParameters): RowStream
  queryStream(sql: string | SqlQuery, params?: QueryParameters): RowStream<RowMode>
  prepare(sql: string, callback: (err: Error | null, stmt: ODBCStatement) => void): void
  prepare(sql: string): Promise<ODBCStatement>
  beginTransaction(callback?: (err?: Error | null) => void): Promise<void> | void
  commitTransaction(callback?: (err?: Error | null) => void): Promise<void> | void
  rollbackTransaction(callback?: (err?: Error | null) => void): Promise<void> | void
  close(callback?: (err?: Error | null) => void): Promise<void> | void
  setIsolationLevel(isolationLevel: number): boolean
  setAttr(attributeName: number | string, value: any, callback?: (err?: Error | null) => void): Promise<boolean> | void
  getInfo(infoType: number | string, callback?: (err: Error | null, value: any) => void): Promise<any> | void
}

export class CompatPool {
  constructor(config?: JsPoolConfig | IbmDbPoolOptions)
  connect(callback?: (err?: Error | null) => void): Promise<void> | void
  warmup(callback?: (err: Error | null, created?: number) => void): Promise<number> | void
  query(sql: string, params: QueryParameters | null | undefined, options: QueryOptions<'array'>): Promise<QueryResult<'array'>>
  query(sql: string, params?: QueryParameters | null, options?: QueryOptions<'object'> | null): Promise<QueryResult>
  query(sql: string, params: QueryParameters | null | undefined, options: QueryOptions | null | undefined): Promise<QueryResult<RowMode>>
  query(sql: string, params: QueryParameters | null | undefined, options: QueryOptions<'array'>, callback: QueryCallback<'array'>): void
  query(sql: string, params: QueryParameters | null | undefined, options: QueryOptions<'object'> | null | undefined, callback: QueryCallback): void
  query(sql: string, params: QueryParameters | null | undefined, options: QueryOptions | null | undefined, callback: QueryCallback<RowMode>): void
  query(sql: string, callback: QueryCallback): void
  query(sql: string, params: QueryParameters | null | undefined, callback: QueryCallback): void
  acquire(): Promise<Client>
  acquire(callback: (err: Error | null, client: Client) => void): void
  release(client: Client | JsClient, callback?: (err?: Error | null) => void): Promise<void> | void
  close(callback?: (err?: Error | null) => void): Promise<void> | void
  idleCount(callback?: (err: Error | null, count?: number) => void): Promise<number> | void
  activeCount(callback?: (err: Error | null, count?: number) => void): Promise<number> | void
  totalCount(callback?: (err: Error | null, count?: number) => void): Promise<number> | void
  maxConnections(callback?: (err: Error | null, count?: number) => void): number | void
  open(connectionString: ConnectionString, callback: (err: Error | null, conn: Database) => void): void
  open(connectionString: ConnectionString): Promise<Database>
  init(size: number, connectionString: ConnectionString): boolean
  initAsync(size: number, connectionString: ConnectionString, callback?: (err?: Error | null) => void): Promise<void> | void
  setMaxPoolSize(size: number): boolean
  setConnectTimeout(timeout: number): boolean
}

export const IbmDbPool: typeof CompatPool

export default function createDatabase(options?: Record<string, any>): Database
export function open(connectionString: ConnectionString, callback: (err: Error | null, conn: Database) => void): void
export function open(connectionString: ConnectionString, options: Record<string, any>, callback: (err: Error | null, conn: Database) => void): void
export function open(connectionString: ConnectionString, options?: Record<string, any>): Promise<Database>
export function close(db?: any): void
export function debug(value: boolean): boolean
export function convertRowsToColumns(rows: any[][]): { params: any[]; ArraySize: number }
