// Re-export NAPI-generated types with clean names.
// index.d.ts is auto-generated by napi build; do not edit it directly.

export {
  JsConnectionConfig as ConnectionConfig,
  JsQueryResult as QueryResult,
  JsColumnInfo as ColumnInfo,
  JsServerInfo as ServerInfo,
  JsPoolConfig as PoolConfig,
  JsClient,
  JsPool,
  JsPreparedStatement,
  JsTransaction,
} from './index.js'

export {
  JsClient as NativeClient,
  JsPool as NativePool,
  JsPreparedStatement as NativePreparedStatement,
  JsTransaction as NativeTransaction,
} from './index.js'

import type {
  JsClient,
  JsConnectionConfig,
  JsQueryResult,
  JsServerInfo,
  JsPoolConfig,
  JsColumnInfo,
} from './index.js'

export type ConnectionString = string | Record<string, any>
export type BinaryParameter = Uint8Array | ArrayBuffer | number[]
export type QueryParameter = string | number | boolean | null | BinaryParameter
export type QueryParameters = QueryParameter[]

export interface IbmDbPoolOptions {
  maxPoolSize?: number
  maxConnections?: number
  connectTimeout?: number
  queryTimeout?: number
  idleTimeout?: number
  maxLifetime?: number
  healthCheckInterval?: number
  currentSchema?: string
  fetchSize?: number
  ssl?: boolean
  rejectUnauthorized?: boolean
  sslClientHostnameValidation?: string
}

export class Client {
  constructor(config: JsConnectionConfig)
  connect(): Promise<void>
  query(sql: string, params?: QueryParameters | undefined | null): Promise<JsQueryResult>
  prepare(sql: string): Promise<PreparedStatement>
  beginTransaction(): Promise<Transaction>
  close(): Promise<void>
  serverInfo(): Promise<JsServerInfo>
}

export class Pool {
  constructor(config?: JsPoolConfig | IbmDbPoolOptions)
  connect(callback?: (err?: Error | null) => void): Promise<void> | void
  warmup(callback?: (err: Error | null, created?: number) => void): Promise<number> | void
  query(sql: string, params?: QueryParameters): Promise<any>
  query(sql: string, callback: (err: Error | null, result: any) => void): void
  query(sql: string, params: QueryParameters, callback: (err: Error | null, result: any) => void): void
  acquire(): Promise<Client>
  acquire(callback: (err: Error | null, client: Client) => void): void
  release(client: Client | JsClient, callback?: (err?: Error | null) => void): Promise<void> | void
  close(callback?: (err?: Error | null) => void): Promise<void> | void
  idleCount(): Promise<number>
  activeCount(): Promise<number>
  totalCount(): Promise<number>
  maxConnections(callback?: (err: Error | null, count?: number) => void): number | void
  open(connectionString: ConnectionString, callback: (err: Error | null, conn: Database) => void): void
  open(connectionString: ConnectionString): Promise<Database>
  init(size: number, connectionString: ConnectionString): boolean
  initAsync(size: number, connectionString: ConnectionString, callback?: (err?: Error | null) => void): Promise<void> | void
  setMaxPoolSize(size: number): boolean
  setConnectTimeout(timeout: number): boolean
}

export class Db2Pool {
  constructor(config: JsPoolConfig)
  connect(): Promise<void>
  warmup(): Promise<number>
  query(sql: string, params?: QueryParameters | undefined | null): Promise<JsQueryResult>
  acquire(): Promise<Client>
  release(client: Client | JsClient): Promise<void>
  close(): Promise<void>
  idleCount(): Promise<number>
  activeCount(): Promise<number>
  totalCount(): Promise<number>
  maxConnections(): number
}

export class PreparedStatement {
  execute(params?: QueryParameters | undefined | null): Promise<JsQueryResult>
  executeBatch(paramRows: Array<QueryParameters>): Promise<JsQueryResult>
  close(): Promise<void>
}

export class Transaction {
  query(sql: string, params?: QueryParameters | undefined | null): Promise<JsQueryResult>
  prepare(sql: string): Promise<PreparedStatement>
  commit(): Promise<void>
  rollback(): Promise<void>
}

export interface Sqlca {
  rowCount: number
  columns: JsColumnInfo[]
  diagnostics: string[]
}

export type IbmDbCallback<T> = (err: Error | null, value: T, sqlca?: Sqlca) => void

export class ODBCResult {
  rows: any[]
  columns: JsColumnInfo[]
  rowCount: number
  diagnostics: string[]
  fetch(callback: (err: Error | null, row: any | false) => void): void
  fetch(): Promise<any | false>
  fetchAll(callback: (err: Error | null, rows: any[]) => void): void
  fetchAll(): Promise<any[]>
  fetchN(count: number, callback: (err: Error | null, rows: any[]) => void): void
  fetchN(count: number): Promise<any[]>
  close(callback?: (err?: Error | null) => void): Promise<void> | void
}

export class ODBCStatement {
  bind(params: QueryParameters, callback?: (err?: Error | null) => void): Promise<void> | void
  execute(callback: (err: Error | null, result: ODBCResult, outparams?: any) => void): void
  execute(params?: QueryParameters): Promise<ODBCResult>
  execute(params: QueryParameters, callback: (err: Error | null, result: ODBCResult, outparams?: any) => void): void
  executeNonQuery(params?: QueryParameters): Promise<number>
  executeNonQuery(params: QueryParameters, callback: (err: Error | null, rowCount: number) => void): void
  close(callback?: (err?: Error | null) => void): Promise<void> | void
}

export class Database {
  open(connectionString: ConnectionString, callback: (err: Error | null, result?: boolean) => void): void
  open(connectionString: ConnectionString, options: Record<string, any>, callback: (err: Error | null, result?: boolean) => void): void
  open(connectionString: ConnectionString, options?: Record<string, any>): Promise<boolean>
  query(sql: string | { sql: string; params?: QueryParameters; noResults?: boolean }, callback: IbmDbCallback<any[]>): void
  query(sql: string | { sql: string; params?: QueryParameters; noResults?: boolean }, params?: QueryParameters): Promise<any[]>
  query(sql: string | { sql: string; params?: QueryParameters; noResults?: boolean }, params: QueryParameters, callback: IbmDbCallback<any[]>): void
  queryResult(sql: string, callback: (err: Error | null, result: ODBCResult, outparams?: any) => void): void
  queryResult(sql: string, params?: QueryParameters): Promise<ODBCResult>
  queryResult(sql: string, params: QueryParameters, callback: (err: Error | null, result: ODBCResult, outparams?: any) => void): void
  queryStream(sql: string, params?: QueryParameters): any
  prepare(sql: string, callback: (err: Error | null, stmt: ODBCStatement) => void): void
  prepare(sql: string): Promise<ODBCStatement>
  beginTransaction(callback?: (err?: Error | null) => void): Promise<void> | void
  commitTransaction(callback?: (err?: Error | null) => void): Promise<void> | void
  rollbackTransaction(callback?: (err?: Error | null) => void): Promise<void> | void
  close(callback?: (err?: Error | null) => void): Promise<void> | void
  setIsolationLevel(isolationLevel: number): boolean
  setAttr(attributeName: number | string, value: any, callback?: (err?: Error | null) => void): Promise<boolean> | void
  getInfo(infoType: number | string, callback?: (err: Error | null, value: any) => void): Promise<any> | void
}

export class CompatPool {
  constructor(config?: JsPoolConfig | IbmDbPoolOptions)
  connect(callback?: (err?: Error | null) => void): Promise<void> | void
  warmup(callback?: (err: Error | null, created?: number) => void): Promise<number> | void
  query(sql: string, params?: QueryParameters): Promise<any>
  query(sql: string, callback: (err: Error | null, result: any) => void): void
  query(sql: string, params: QueryParameters, callback: (err: Error | null, result: any) => void): void
  acquire(): Promise<Client>
  acquire(callback: (err: Error | null, client: Client) => void): void
  release(client: Client | JsClient, callback?: (err?: Error | null) => void): Promise<void> | void
  close(callback?: (err?: Error | null) => void): Promise<void> | void
  idleCount(callback?: (err: Error | null, count?: number) => void): Promise<number> | void
  activeCount(callback?: (err: Error | null, count?: number) => void): Promise<number> | void
  totalCount(callback?: (err: Error | null, count?: number) => void): Promise<number> | void
  maxConnections(callback?: (err: Error | null, count?: number) => void): number | void
  open(connectionString: ConnectionString, callback: (err: Error | null, conn: Database) => void): void
  open(connectionString: ConnectionString): Promise<Database>
  init(size: number, connectionString: ConnectionString): boolean
  initAsync(size: number, connectionString: ConnectionString, callback?: (err?: Error | null) => void): Promise<void> | void
  setMaxPoolSize(size: number): boolean
  setConnectTimeout(timeout: number): boolean
}

export const IbmDbPool: typeof CompatPool

export default function createDatabase(options?: Record<string, any>): Database
export function open(connectionString: ConnectionString, callback: (err: Error | null, conn: Database) => void): void
export function open(connectionString: ConnectionString, options: Record<string, any>, callback: (err: Error | null, conn: Database) => void): void
export function open(connectionString: ConnectionString, options?: Record<string, any>): Promise<Database>
export function close(db?: any): void
export function debug(value: boolean): boolean
export function convertRowsToColumns(rows: any[][]): { params: any[]; ArraySize: number }
